config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get '/dashboard' => 'home#dashboard', as: 'dashboard'

  resources :prompts do
    resources :prompt_responses
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prompt.rb
class Prompt < ApplicationRecord

  has_many :users, :through => :prompt_responses

  validates_presence_of :prompt_question

end

app/models/prompt_response.rb
class PromptResponse < ApplicationRecord
  belongs_to :user
  belongs_to :prompt
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :prompts, :through => :prompt_responses

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    dashboard_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def dashboard
    @user = current_user
    @response_count = PromptResponse.where(user_id: current_user.id).count
    @received_count = PromptResponse.where("luver_id = ? AND send_date <= ?", current_user.id, Date.today()).count

    @luv_notes_ready = []
    PromptResponse.where("luver_id = ? AND send_date <= ? AND send_date <= ?", current_user.id, Date.today(), Date.today + 30).each do |response|
      @luv_notes_ready << response
    end

    all_prompts = []

    PromptResponse.find_each do |response|
      if response.user_id == current_user.id
        prompt_to_remove = Prompt.find(response.prompt_id)
        all_prompts << prompt_to_remove
      end
    end

    prompts = Arel::Table.new(:prompts)

    @prompts = Prompt.where(prompts[:id].not_in all_prompts)
  end
end

app/controllers/prompt_responses_controller.rb
class PromptResponsesController < ApplicationController

  before_action :ensure_time, only: [:show]
  before_action :ensure_luver, only: [:show]

  def new
    @prompt = Prompt.find(params[:prompt_id])
    @prompt_response = PromptResponse.new
  end

  def create
    @prompt_response = PromptResponse.new(prompt_response_params)
    if @prompt_response.save!
      @prompt_response.user_id = current_user.id
      @prompt_response.luver_id = current_user.luver_id
      @prompt_response.prompt_id = params[:prompt_id]
      @prompt_response.send_date = generate_random_time()
      @prompt_response.save!

      user = current_user
      luver = User.find(current_user.luver_id)
      email = luver.email
      prompt_response_date = @prompt_response.send_date

      NoteNotificationMailer.notification_email(user, luver, email).deliver_later(wait_until: prompt_response_date)

      redirect_to root_path, notice: "Response saved."
    else
      render :new
    end
  end

  def show
    @prompt_response = PromptResponse.find(params[:id])

    @prompt = Prompt.find(params[:prompt_id])

    @luver = User.find(current_user.luver_id)
  end

  private

  def prompt_response_params
    params.require(:prompt_response).permit(:prompt_id, :user_id, :send_date, :response, :luver_id)
  end

  def generate_random_time
    date1 = DateTime.now
    date2 = DateTime.new(2021,9,15)

    time = Time.at((date2.to_time.to_f - date1.to_time.to_f)*rand + date1.to_time.to_f)
    return time
  end

  def ensure_time
    @prompt_response = PromptResponse.find(params[:id])
    if Time.now.to_i <= @prompt_response.send_date.to_i
      redirect_to root_path, notice: "You cannot view this prompt response because it's not time yet"
    end
  end

  def ensure_luver
    @prompt_response = PromptResponse.find(params[:id])
    if @prompt_response.luver_id != current_user.id
      redirect_to root_path, notice: "You cannot view this prompt response because you're not the luver"
    end
  end

end

app/controllers/prompts_controller.rb
class PromptsController < ApplicationController

  def new
    @prompt = Prompt.new
  end

  def create
    @prompt = Prompt.new(prompt_params)

    respond_to do |format|
      if @prompt.save
        format.html { redirect_to root_path, notice: "Prompt saved." }
        format.json { render :show, status: :created, location: @prompt}
      else
        format.html { render :new }
        format.json { render json: @prompt.errors, status: :unprocessable_entity}
      end
    end
  end

  private
  def set_prompt
    @prompt = Prompt.find(params[:id])
  end

  def prompt_params
    params.require(:prompt).permit(:prompt_question)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert', style: 'padding-top: 35px;') do
        concat(content_tag(:button, class: 'btn btn-info', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/dashboard.html.erb
<div class="container lg-margin-top">
  <div class="row">
    <div class="col-md-12 text-center">
      <h3>Your luver is: <%= User.find(@user.luver_id).email %></h3>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <h5>Created <span class="badge bg-primary"><%= @response_count %> </span></h5>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <h5>Received <span class="badge bg-success"><%= @received_count %> </span></h5>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <h5>Available to view <span class="badge bg-danger"><%= @luv_notes_ready.count %> </span></h5>
    </div>
  </div>
</div>
<div class="container md-margin-top">
  <div class="row">
    <div class="col-md-6">
      <% if @luv_notes_ready.any? %>
        <% @luv_notes_ready.each do |note| %><br />
          <%= link_to "View Note!", prompt_prompt_response_path(note.prompt_id, note), class: 'btn btn-primary'  %><br />
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="container sm-margin-top">
  <div class="row">
    <div class="col-md-6">
      <h4>Send a Luv Note</h4>
      <% if @prompts.empty? %>
        <p>No new prompts to respond to</p>
      <% end  %>
      <% @prompts.each do |prompt| %><br /><br />
        <div class="card card-body bg-light">
          <p><%= prompt.prompt_question %></p>
          <%= link_to "Answer prompt", new_prompt_prompt_response_path(prompt), class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container-lg">
  <div class="row">
    <div class="col-md-12 text-center">
      <h2>Sam's Luv Notes</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-center">
      <%= image_tag("mexico.jpg", class: "img-fluid") %>
    </div>
  </div>
  <div class="row sm-margin-top">
    <div class="col-md-12 text-center">
      <%= link_to "Sign in", new_user_session_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light sm-padding-left">
  <%= link_to "Luv Notes", dashboard_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", dashboard_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to "Sign out", destroy_user_session_path, :method => 'delete', :class => 'btn btn-primary' %>
        <% else %>
          <%= link_to "Sign in", new_user_session_path, :class => "btn btn-danger" %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LuvNotes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render "layouts/navigation" %>

  <%= flash_messages %>
  <%= yield %>
  </body>
</html>

app/views/prompt_responses/_form.html.erb
<div class="prompt-response-div">
  <%= form_for [@prompt, @prompt_response], url: prompt_prompt_responses_path do |f| %>
    <%= f.hidden_field(:user_id, :value => current_user.id) %>
    <%= f.hidden_field(:prompt_id, :value => @prompt.id) %>
    <h3><%= Prompt.find(params[:prompt_id]).prompt_question %></h3>
    <div class="form-group">
      <div class="field">
        <%= f.text_area :response, rows: 20, cols: 70, class: 'form-control' %>
      </div><br />
      <div class="actions">
        <%= f.submit class: 'btn btn-lg btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/prompt_responses/new.html.erb
<%= render 'form' %>

app/views/prompt_responses/show.html.erb
<div class="prompt-response-div">
  <h2><%= @prompt.prompt_question %></h2>
  <h3 class="prompt-response"><%= @prompt_response.response %></h3>
  <h4>With Luv, <%= @luver %></h4>
  <h5>Created at: <%= @prompt_response.created_at %></h5>
</div>